### ISSUE TITLE
It seems like the default value in .cfg files is not taken into account for atleast modules/acc*.cfg

### ISSUE THREAD

**Issue by BenjaminSoelberg** [BenjaminSoelberg/openchronos-ng-elf#24]
It seems like the default value in .cfg files is not taken into account for atleast modules/acc*.cfg. Investigate!

Above text moved from todo.txt

**Comment by quoraquestions** [comment]
hey, 

the issue is related to
https://stackoverflow.com/questions/12750778/booleans-in-configparser-always-return-true

the way to cause a particular feature not to be selected by default is to remove the

default: false 

section from the config file.

Regards,
Menehune

**Comment by BenjaminSoelberg** [comment]
effa196889eb84f280a54cd241f92e0d1137acc1
