### ISSUE TITLE
Music modules sounds wrong

### ISSUE THREAD

**Issue by BenjaminSoelberg** [BenjaminSoelberg/openchronos-ng-elf#5]
... at least when run on the black pcb version of the watch

**Comment by quoraquestions** [comment]
Sounds wrong on White 1.1 Version too :(

**Comment by BenjaminSoelberg** [comment]
Re-add the original SMB tune or find a better one.
(was changed to a debug tune during my testing)

**Comment by BenjaminSoelberg** [comment]
(was changed to a debug tune during my testing)

**Comment by BenjaminSoelberg** [comment]
For later use : http://mines.lumpylumpy.com/Electronics/Computers/Software/Cpp/MFC/RingTones.RTTTL
Has a lot of RTTTL tunes

**Comment by BenjaminSoelberg** [comment]
Fixed in https://github.com/BenjaminSoelberg/openchronos-ng-elf/commit/c664f485a0f26f19ba5f6fbb908dbaa9a0ef22b8
