### ISSUE TITLE
Often accidentally entering "set time" causes problems

### ISSUE THREAD

**Issue by BenjaminSoelberg** [BenjaminSoelberg/openchronos-ng-elf#56]
I often get into a situation where I have accidentally enter "set time" menu.
This causes the clock to stop running and when I return the clock is off by some but understandabe amount.
This is not a very good situation to be in and I suggest that we return to normal mode (exiting the "set time") if no button has been touched for say 30 sec.
I also suggest restoring the "correct time" in this case (if not changes has been made)

This is up for discussion!

**Comment by quoraquestions** [comment]
Agree 👍 the watch should return to normal function 'out of edit mode' after a timeout

**Comment by BenjaminSoelberg** [comment]
Hard coded timeout has been set to 10 sec both for menu selection and while setting time
