### ISSUE TITLE
Black PCB: Acceleration, simpliciTI, RF AP

### ISSUE THREAD

**Issue by yhaenggi** [BenjaminSoelberg/openchronos-ng-elf#58]
Do the acceleration, simpliciTI and the communication with the RF AP work for the early (black pcb) versions?

**Comment by cynum** [comment]
Hi!
I recently started to work on my own small project and I have also started to work with openchronos.
First I used the black PCB where communication with the AP worked fine.
Acceleration seems also to work, the code is not finished however.
I recently lost my old black PCB chronos unfortunately, and now I am having trouble to get the communication with the AP to work :/. I don't know if anyone was using openchronos with the white PCBs. Should it work just as well? I am still trying to get the white one working, especially wireless updates...

**Comment by cynum** [comment]
Ok, firstly I found the black PCB watch again :-)
Secondly, all seems to more or less work. I have had the idea that my black PCB was a 433MHz model. So it didn't work anymore when I installed the 433MHz software. With the correct software communication to the AP works with the black and white PCB. Also the black watch with the white dongle and vice versa. No problem with the black one.

Just the accel code needs to be changed to work with the different accel sensor that is in the white PCB. I will share that once I have it.

Cheers

**Comment by BenjaminSoelberg** [comment]
I have started working on the project again.

That sounds very nice, please share the code when you get it to work.

The whole black vs white vs rf dongles is a huge problem.
I myself has the black version in a 433 mhm version i think.
I have to restart RF wireless update a few times to get it to work or unplugging and plugging the dongle again. 

Please also remember to try a new battery in the watch if it has less than around 88% left.
Seems like RF only work with the top 12% of the battery power.

**Comment by BenjaminSoelberg** [comment]
K1773R simpliciTI was removed due to ram constraints.
My primary focus has been to make it a usable watch.
But the basic RF do work.
The Acceleration code has not been looked at since I took over the project.
Neither has the pressure sensor code.

vti_as.c
vti_as.h
vti_ps.c
vti_ps.h
