### ISSUE TITLE
docs don't say who to contact for slack access

### ISSUE THREAD

**Issue by rfc6919** [BenjaminSoelberg/openchronos-ng-elf#60]
README.md says:

> Join us at Slack Team Channel:
> 
> https://openchronos.slack.com

and Slack says:

> Don't have an account on this workspace yet?
> Contact the workspace administrator for an invitation

but there's no indication who to contact for an invitation

**Comment by BenjaminSoelberg** [comment]
Hi and thanks.

Just send me your email address and i'll also fix the doc.

**Comment by bfasy** [comment]
I'm confused as to why this is closed, as the message is still there, and I am not sure who the adminstrator is of a slack group that I am trying to join.
