### ISSUE TITLE
Alarm module not working. 

### ISSUE THREAD

**Issue by BenjaminSoelberg** [BenjaminSoelberg/openchronos-ng-elf#7]
Alarm is not firing at set time.

**Comment by quoraquestions** [comment]
looks like rtca_enable_alarm is not enabled 

 static void print_mm (void)
 {
@@ -181,7 +181,7 @@ static void num_pressed()
        if (alarm_state.alarm) {
                display_symbol(0, LCD_ICON_ALARM, SEG_ON);
                sys_messagebus_register(&alarm_event, SYS_MSG_RTC_ALARM);
-// Not ready for prime time yet!               rtca_enable_alarm();
+               rtca_enable_alarm();
        } else {
                display_symbol(0, LCD_ICON_ALARM, SEG_OFF);
        }

**Comment by BenjaminSoelberg** [comment]
True, I did this as there is no real alarm handler. Along the lines of "bip bip, wait a sec, bip bip..". This should be done in a statemachine with no delay usage. Some sort of button hook should also be made to deselect (or snoozing)  the alarm when firing. Never got around to implement it. Was also thinking about making the music module timer callback based in order to drop the usage of blocking delay function. Same approach could be used in the alarm handler (or just call play function in buzzer driver which would handle it by it self).

**Comment by BenjaminSoelberg** [comment]
working on it right now, now that the global button pressed message  and peek button functions has been implemented. Need to add an interrupt driven buzzer_play function to play an 'alarm' tune while the rest of the watch is still running in main loop.

**Comment by BenjaminSoelberg** [comment]
e4caadf Benjamin Sølberg on 3/5/17 at 11:08 PM Added alarm functionality to make it sound for 30 sec or stop by pressing any button
bab85c6 Benjamin Sølberg on 3/4/17 at 12:11 AM Async buzzer play function with LPM handeling
